CREATE TABLE IF NOT EXISTS `lecture_tb` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL,
  `explain` varchar(1000) DEFAULT NULL,
  `major` tinyint(1) NOT NULL,
  `plan` varchar(3000) DEFAULT NULL,
  `date` varchar(30) DEFAULT NULL,
  `credit` smallint(6) NOT NULL,
  `time` smallint(6) NOT NULL,
  `face_to_face` tinyint(1) NOT NULL,
  `max_capacity` int(11) NOT NULL,
  `recommend_grade` smallint(6) NOT NULL,
  `semester` smallint(6) NOT NULL,
  `subject_id` int(11) NOT NULL,
  `professor_id` int(11) NOT NULL,
  `lecture_room_number` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `lecture_room_number` (`lecture_room_number`),
  KEY `professor_id` (`professor_id`),
  KEY `subject_id` (`subject_id`),
  CONSTRAINT `lecture_tb_ibfk_1` FOREIGN KEY (`subject_id`) REFERENCES `subject_tb` (`id`),
  CONSTRAINT `lecture_tb_ibfk_2` FOREIGN KEY (`professor_id`) REFERENCES `professor_tb` (`id`),
  CONSTRAINT `lecture_tb_ibfk_3` FOREIGN KEY (`lecture_room_number`) REFERENCES `lecture_room_tb` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=501 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
